#!/bin/bash
groups=$(ls -d progetti/gruppo*);
for g in $groups; do
	printf "cleaning %s\n" $g;
	cd $g;
	find . -type f ! -name "*.*" -delete;
	rm -fr *[!\(.nasm\|.c\|.pdf\)];
	rm -fr .[!.]*;
	cd ../..;
done;
